# Generated by Django 4.1.1 on 2022-10-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentmarketorder",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="currentmarketorder",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="limitorder",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="limitorder",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="tradehistory",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="tradehistory",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="fiat",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="stocks",
            field=models.FloatField(default=0),
        ),
    ]
