# Generated by Django 4.1.1 on 2022-10-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_currentmarketorder_price_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CurrentMarketOrder",
            new_name="CurrentMarketPrice",
        ),
        migrations.AddField(
            model_name="tradehistory",
            name="type",
            field=models.CharField(
                choices=[("buy", "buy"), ("sell", "sell")], default="buy", max_length=50
            ),
        ),
    ]
