# Generated by Django 4.1.1 on 2022-10-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_currentmarketorder_currentmarketprice_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tradehistory",
            old_name="buyer",
            new_name="user1",
        ),
        migrations.RenameField(
            model_name="tradehistory",
            old_name="seller",
            new_name="user2",
        ),
    ]
